name: Build And Push
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: vimtor/action-zip@v1
        with:
          files: assets/ pack.mcmeta pack.png
          dest: ./build/Pack.zip
          recursive: false
      - name: Update hash.txt
        run: |
          sha1sum ./build/Pack.zip > ./build/hash.txt
      - name: Push
        run: |
          git config advice.addIgnoredFile false
          git config --global user.email "githubactions@github.com"
          git config --global user.name "Github-Actions[bot]"
          git status
          git add -f ./build/Pack.zip
          git add -f ./build/hash.txt
          git commit -m "Update"
          git push origin main
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write .
