name: Build And Push
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-prettify-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: vimtor/action-zip@v1
        with:
          files: assets/ pack.mcmeta pack.png
          dest: ./build/Pack.zip
          recursive: false
      - name: Update hash.txt
        run: |
          sha1sum ./build/Pack.zip > ./build/hash.txt
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write .
          commit_message: "Prettify and Update Pack"
